---
title: "Plots"
author: "Arlette Hall"
date: "2026-03-03"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

HW7 Summarize & Regression Lines
```{r}
#count number of males
nmales <- data %>%
  filter(sex=="m") %>%
  nrow()

#custom summary
data %>%
  filter(sex=="f" & years_of_sample_collection=="1966-68") %>%
  select(estimated_age_years, sex) %>%
  summarize(mean_age_f_1966t68=mean(estimated_age_years, na.rm=T),
            median_age_f_1966t68=median(estimated_age_years, na.rm=T),
            sd_age_f_1966t68=sd(estimated_age_years, na.rm=T),
            total=n())

#multiple regression lines on one plot (color=A)
ggplot(data=elephants,
       mapping=aes(x=estimated_age_years, y=tusk_length_in_cm,
                   color=years_of_sample_collection))+
  geom_point(na.rm=T)+
  geom_smooth(method=lm, se=T, na.rm=T)+
  labs(x="Estimated Age (yrs)", y="Tusk Length (cm)",
       title="Estimated Age vs Tusk Length by Collection Period")
```

HW8
```{r}
#mutate across
fisheries_clean <- fisheries_clean %>%
  mutate(across(c(), as.factor))

#count number of types in one variable
fisheries_clean %>%
  summarize(n_species=n_distinct(common_name))
```


HW9 Pivot & Separate:
```{r}
#wider
data_wide <- data_long %>%
  pivot_wider(names_from = "date",
              values_from = "enterococci_cfu_100ml")
#longer
data_wide %>%
  pivot_longer(-site, #exclude this one
               names_to = "date",
               values_to = "enterococci_cfu_100ml")
#separate
data_long <- data_long %>%
  separate(date, into=c("day", "month", "year"), sep="/")

#multiple groupings
data_long %>%
  group_by(year, site) %>%
  summarize(avg_enterococci_cfu_100ml = mean(enterococci_cfu_100ml, na.rm=T,),
            .groups='keep')
```


HW10 Plots
```{r}
#cancels scientific notation for the session
options(scipen=999)
```

```{r}
#observation count by X
data %>%
  count(X, sort=T)

data %>%
  count(order, sort=T) %>%
  ggplot(mapping=aes(x=X, y=n, fill=X, fill=X))+
  geom_col(na.rm=T)+
  coord_flip()+
  labs(x="X", y="Number of Observations", title="Number of Observations per X", fill="X")
```

```{r}
#bar plot of the mean mass for each X
data %>%
  group_by(X) %>%
  summarize(mean_mass = mean(mass, na.rm=T)) %>%
  arrange(desc(mean_mass))

data %>%
  group_by(X) %>%
  summarize(mean_mass = mean(mass, na.rm=T)) %>%
  ggplot(mapping=aes(x=reorder(X, mean_mass), y=mean_mass, fill=X))+
  geom_col(na.rm=T)+
  coord_flip()+
  scale_y_log10()+
  labs(x="X", y="Mean Mass", title="Mean Mass per X")
```

```{r}
#scatter plots = comparisons of two continuous variables
data %>%
  ggplot(aes(x=X, y=Y))+
  geom_point(color=X, shape=X, alpha=0.7, size=2, na.rm=T)+
  geom_smooth(method=lm, se=T, na.rm=T)+
  scale_y_log10()+
  labs(x="X", y="Y", title="X vs Y")
```

```{r}
#boxplot = visualize a range
data %>%
  ggplot(aes(x=X, y=log10(Y), fill=X))+  #another way of scaling
  geom_boxplot(na.rm=T)+
  coord_flip()+
  labs(x="X", y="Log of Y", title="Log of Y by X")
```

```{r}
#barplot
data %>%
  ggplot(aes(x=X, fill=A))+
  geom_bar(position="dodge", na.rm=T)+
  coord_flip()+
  labs(x="X", y=NULL, title="Number of Observations per X", fill="A")

#scale all bars to percentage
data %>%
  na.omit() %>%  #remove NAs
  ggplot(aes(x=X, fill=A))+
  geom_bar(position=position_fill())+
  scale_y_continuous(labels=scales::percent)+
  coord_flip()+
  labs(x="X", y=NULL, title="Number of Observations per X", fill="A")
```

```{r}
#axis labels & fun
data %>%
  ggplot()+
  theme_minimal()+
  theme(plot.title=element_text(size=rel(1.5), hjust=.5, face = "bold"),
        axis.title.x=element_text(angle=45, hjust=0.9, face = "bold"),
        axis.text.x=element_text(angle=45, hjust=0.9, face = "bold"),
        legend.position = "none")+
  scale_x_continuous(breaks=seq(1925, 2025, by=10))
```


HW11 Line & Density plots
```{r}
#read in filtered data
gapminder <- read_csv("data/gapminder.csv") %>% 
  clean_names() %>% 
  filter(between(year, 1925, 2025))

library(paletteer)  #for plot themes

#line plot
gapminder %>%
  filter((year >= 1925 & year <= 2025) & country=="India") %>%
  ggplot(aes(x=year, y=pop/1000000))+
  geom_line(color="purple3")+
  labs(x="Year",
       y="Population (in millions)",
       title="India: Population Growth, 1925-2025")+
  theme_minimal()+
  theme(plot.title=element_text(hjust=0.5, size=rel(1.3), face="bold"),
        axis.title.x=element_text(face="bold"),
        axis.title.y=element_text(face="bold"))+
  scale_x_continuous(breaks=seq(1925, 2025, by=10))

#mutate numeric to factor to use as fill, color or shape
#density plot
gapminder %>%
  filter(year==1925 | year==2025) %>%
  mutate(year=factor(year)) %>%
  ggplot(aes(x=lex, color=year, fill=year))+
  geom_density(alpha=0.3, na.rm=T)+
  labs(x="Life Expectancy (Yrs)", y=NULL,
       title="Distribution of Life Expectancy, 1925 & 2025",
       color="Year", fill="Year")+
  theme_minimal()+
  theme(plot.title=element_text(hjust=0.5, size=rel(1.3), face="bold"),
        axis.title.x=element_text(face="bold"),
        axis.title.y=element_text(face="bold"))+
  scale_x_continuous(breaks=seq(20, 90, by=10))

```


skip HW12


HW13_1 Check for & Remove NAs:
```{r}
library(naniar)

#NA summary
data_no_na %>%
  miss_var_summary()

#count number of NAs
data_no_na %>%
  miss_var_summary() %>%
  summarize(n_miss_total = sum(n_miss))
```


```{r}
#replace -999 with NA
data_no_na <- amniota %>%
  replace_with_na_all(condition = ~.x %in% c(-999))

#replace -30258.71100 with NA
amniota_no_na <- amniota_no_na %>%
  mutate(female_maturity_d=na_if(female_maturity_d, -30258.71100))

#just in case there are hidden issues in character columns
data_no_na <- data_no_na %>%
  replace_with_na_all(condition = ~.x %in% c(common_na_strings))

#extra note
data %>%
  replace_with_na_all(condition = ~.x %in% c(common_na_strings, common_na_numbers)) %>%
  mutate(newborn=na_if(newborn, "not measured"))
```

HW13_2 Joining Data & Managing Dates:
```{r}
table_A <-read_csv("~/Desktop/BIS15L_W26_aehall/lab13/data/table_A.csv")
table_B <- read_csv("~/Desktop/BIS15L_W26_aehall/lab13/data/table_B.csv")

#keeps all rows in both tables
inner_join(table_A, table_B, by="customer_ID")
#keeps all rows in first table
left_join(table_A, table_B, by="customer_ID")
#keeps all rows in second table
right_join(table_A, table_B, by="customer_ID")
#keeps all rows
full_join(table_A, table_B, by="customer_ID")

#keeps rows in first table that are missing from second
#use to troubleshoot
anti_join(table_A, table_B, by="customer_ID")
```

```{r}
library("lubridate")

today()
now()

dateformat1 <- "20200922"
dateformat2 <- "09-22-2020"
dateformat3 <- "22/09/2020"
dateformat4 <- "09-22-2020 17:00:00"
dateformat5 <- "20200922 170000"

#use within mutate
ymd(dateformat1)
mdy(dateformat2)
dmy(dateformat3)
mdy_hms(dateformat4)
ymd_hms(dateformat5)

#use mutate to change date format
data <- data %>%
  mutate(date=dmy(date))
```

HW14 Maps & Shiny App:
```{r}
library(ggmap)

#register_stadiamaps("1ad11010-4c59-42b0-a160-0dab4e61577f", write = FALSE)

#read in data without NAs & data as numeric
sharks <- read_csv("data/SharkIncidents_1950_2022_220302.csv") %>% 
  clean_names() %>% 
  filter(longitude !="NA" & latitude !="NA") %>%
  mutate(longitude = as.numeric(longitude)) #only if necessary

#get mins and maxes
sharks  %>%
  select(latitude, longitude) %>%
  summary()

#set latitude and longitude ranges, using min's & max's
lat <- c(32.59, 41.56)
long <- c(-124.7, -117.1)
#make bbox with 3% (f=0.03) buffer
bbox <- make_bbox(long, lat, f=0.03)

#load map
map <- get_stadiamap(bbox, maptype = "stamen_terrain", zoom = 7)
ggmap(map)

#example
ggmap(map)+
  geom_point(data=sharks %>%
               filter(injury == "fatal"),
             aes(longitude, latitude), size=0.5, color="black", alpha=0.6)+
  labs(x="Longitude", y="Latitude", title="CA: Fatal Shark Attacks, 1950-2022")+
  theme(plot.title=element_text(size=rel(1.2), hjust=0.5, face="bold"))
```

```{r}
library(leaflet)

ui <- fluidPage(
  radioButtons("x",
              "Select Variable of Interest:",
              choices = c("mode",
                          "depth",
                          "species"),
              selected = "mode"),
  plotOutput("plot",
             width = "500px",
             height = "800px")
)

server <- function(input, output, session) {
  output$plot <- renderPlot({
    sharks_fatal <- sharks %>%
      filter(injury == "fatal" & depth != "N/A")
    
    ggmap(map)+
      geom_point(data=sharks_fatal,
                 aes(x=longitude, y=latitude, shape=.data[[input$x]]),
                 size=2.5,
                 color="red",
                 alpha=0.7,
                 na.rm=T)+
      labs(x="Longitude", y="Latitude", title="CA: Fatal Shark Attacks, 1950-2022")+
      theme(plot.title=element_text(size=rel(1.8), hjust=0.5, face="bold"),
            axis.title.x=element_text(face="bold"),
            axis.title.y=element_text(face="bold"))
  })
  
}

shinyApp(ui, server)
```

